InseeFr/Drama-Queen

drama-queen/src/ui/components/orchestrator/Orchestrator.tsx
fix continue button moving when the loop panel is displayed
=> style : fix continue position in loop

.env.drama.sample, drama-queen/.env, drama-queen/src/bootstrap.tsx, drama-queen/src/ui/components/orchestrator/Orchestrator.tsx, drama-queen/src/vite-env.d.ts, drama-queen/vite.config.ts
add base url as environment variable for images and workers, for integration in Pearl
=> fix: add base url for workers and images

drama-queen/src/core/model/SurveyUnitData.ts, drama-queen/src/ui/components/orchestrator/LoopPanel/LoopPanel.tsx, drama-queen/src/ui/components/orchestrator/Orchestrator.tsx, drama-queen/src/ui/components/orchestrator/lunaticType.ts, drama-queen/src/ui/components/orchestrator/tools/getQueenNavigation.ts
- use getChangedData instead of getData for updating state and data on page changing (with reset)
- use updated data for loopPanel instead of using getData
=> Refactor : get differential data for handling state/data

drama-queen/src/core/usecases/synchronizeData/thunks.ts
The synchronization wasn't actually waiting for the completion of the download of survey-units before creating the complete download event.
Considering that the event redirects to another page, download actually failed
=> fix: early redirection after synchro download

drama-queen/package.json, yarn.lock
=> deps: upgrade lunatic to 2.7.23

drama-queen/src/ui/components/orchestrator/NavBar/NavBar.tsx, drama-queen/src/ui/components/orchestrator/Orchestrator.tsx, drama-queen/src/ui/components/orchestrator/buttons/PrevNext/PrevNext.tsx, drama-queen/src/ui/components/orchestrator/lunaticType.ts, drama-queen/src/ui/components/orchestrator/tools/useContinueBehavior.tsx, drama-queen/src/ui/components/orchestrator/tools/useNavigationButtons.tsx
=> Feat : handle fastforward/next if no answer

drama-queen/package.json, drama-queen/src/ui/components/orchestrator/lunaticStyle.tsx
temp fix for css randomly overriden by lunatic for subsequence in loop, awaiting lunatic v3
=> style: fix lunatic style override

drama-queen/src/ui/components/orchestrator/Menu/Menu.tsx
=> fix: handle menu style when scrolling

drama-queen/src/core/adapters/queenApi/mock.ts, drama-queen/src/core/adapters/queenApi/parserSchema/surveyUnitSchema.ts, drama-queen/src/core/model/SurveyUnit.ts
=> fix: personalization type

drama-queen/src/custom.d.ts, drama-queen/src/ui/pages/External/External.tsx, drama-queen/src/ui/routing/routes.tsx
fix: #240 
⚠️ For this to work, PR #250  must be in the code base.
=> feat(#240): add capmi app to the router rules

drama-queen/src/bootstrap.tsx, drama-queen/src/main.tsx
=> feat(#242): inject externalResources script at start

drama-queen/src/ui/components/orchestrator/Orchestrator.tsx, drama-queen/src/ui/components/orchestrator/tools/functions.tsx
=> feat(#238): add global variables before initalize with Lunatic

drama-queen/src/queen-service-worker.js
External SW is added in condition where VITE_EXTENAL_RESOURCES_URL is defined
fix: #231
=> feat(#231): add external service-worker 

drama-queen/src/ui/components/orchestrator/lunaticStyle.tsx
=> fix: display checkbox boolean

drama-queen/src/ui/components/orchestrator/lunaticStyle.tsx
- similar as https://github.com/InseeFr/Drama-Queen/pull/265
but needed on 2.2
=> fix: display checkbox boolean (2.2)

src/core/adapters/datastore/default.ts, src/core/adapters/queenApi/mock.ts
Filter getAllSurveyUnit method to filter mocked Data in order to avoid sending mockedData to server
=> chore: filter getAllSurveyUnit method to filter mocked Data

src/ui/components/orchestrator/lunaticStyle.tsx
Improve inputs size and police
Also improve globally style of lunatic components and their margin/padding
=> style : improve inputs size & global lunatic components style

package.json, src/core/adapters/queenApi/mockData/surveySample.ts, src/ui/components/orchestrator/lunaticStyle.tsx, yarn.lock
Display components description for displaying components format.
Same style as help declarations.
Needed to upgrade to lunatic 3.4.15 fixing the description not displayed
=> feat: handle components description

src/queen-service-worker.js
Bug due to this: https://github.com/InseeFr/Drama-Queen/pull/311
=> fix: env variable name for sw

index.html
Note that the commitlint took longer than the dev
=> fix: set the default language to french to avoid unwanted translation

src/ui/components/orchestrator/lunaticStyle.tsx
Fix temporaire le temps de modifier les classes css des ronds point pour pouvoir utiliser la surcharge "classique"
=> style: roundabout label & description

src/ui/components/orchestrator/hooks/useQueenNavigation.ts
avoid the fact that getChangedData function from Lunatic changes every input
=> fix: prevent from calling getChangedData on every input

package.json, src/ui/components/orchestrator/Orchestrator.tsx, src/ui/components/orchestrator/lunaticType.ts, src/ui/components/orchestrator/utils/autoNext.test.ts, src/ui/components/orchestrator/utils/autoNext.ts, yarn.lock
We need a Lunatic fix on CheckboxOne type
=> fix: do not auto next a question if a clarification is asked for

package.json, src/components/orchestrator/Orchestrator.tsx, src/components/orchestrator/hooks/controls/useControls.test.ts, src/components/orchestrator/hooks/controls/useControls.ts, src/components/orchestrator/hooks/controls/utils.test.ts, src/components/orchestrator/hooks/controls/utils.ts, src/components/orchestrator/utils/autoNext.test.ts, src/components/orchestrator/utils/autoNext.ts, yarn.lock
~~Must update Lunatic version with new type before merging so it's a draft for now.~~
~~Apart from unhappy TS it works and is ready for review though.~~
=> feat: ignore non mandatory errors on dk or refusal

src/utils/files.test.ts
Mocks of hell, maybe we can do easier...
Just wanted to find out how to make test on a download function
=> test: add tests on json download util

src/components/orchestrator/lunaticStyle.ts
(Same pr as before, I messed up with branches)
=> fix: focus color on roundabout button
